version: "3.4"

services:
    redis:
        image: redis
        ports:
            - "6381:6379"
    db:
        image: postgres:12-alpine
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: zane
        ports:
            - "5434:5432"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
    redis-gui:
        image: rediscommander/redis-commander
        environment:
            - REDIS_HOSTS=local:redis:6379:0:redis_password
        ports:
            - "8089:8081"
volumes:
    db-data:
