openapi: 3.0.3
info:
  title: ZaneOps API
  version: 1.0.0
  description: Your deployment, simplified. Everything handled for you.
paths:
  /api/auth/login/:
    post:
      operationId: login
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginErrorResponse'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginErrorResponse'
          description: ''
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginErrorResponse'
          description: ''
  /api/auth/logout/:
    delete:
      operationId: logout
      tags:
      - auth
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
  /api/auth/me/:
    get:
      operationId: getAuthedUser
      tags:
      - auth
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthedSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
  /api/csrf/:
    get:
      operationId: csrf_retrieve
      description: CSRF cookie view for retrieving CSRF before doing requests
      tags:
      - csrf
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CSRF'
          description: ''
  /api/docker/check-port/:
    post:
      operationId: checkIfPortIsAvailable
      tags:
      - docker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerPortCheckRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DockerPortCheckRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DockerPortCheckRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerPortCheckSuccessResponse'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerPortCheckSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerPortCheckErrorResponse'
          description: ''
  /api/docker/image-search/:
    get:
      operationId: searchDockerRegistry
      parameters:
      - in: query
        name: q
        schema:
          type: string
          minLength: 1
        required: true
      tags:
      - docker
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerImageSearchErrorResponse'
          description: ''
  /api/docker/login/:
    post:
      operationId: dockerLogin
      tags:
      - docker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockerLoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DockerLoginRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DockerLoginRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerLoginSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerLoginErrorResponse'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockerLoginErrorResponse'
          description: ''
  /api/domain/root/:
    get:
      operationId: getRootDomain
      tags:
      - domain
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRootDomain'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
  /api/projects/:
    get:
      operationId: getProjectList
      parameters:
      - in: query
        name: include_archived
        schema:
          type: boolean
          default: false
      - in: query
        name: query
        schema:
          type: string
          default: ''
      - in: query
        name: sort
        schema:
          enum:
          - name_asc
          - updated_at_desc
          type: string
          default: updated_at_desc
          minLength: 1
        description: |-
          * `name_asc` - name ascending
          * `updated_at_desc` - updated_at in descending order
      tags:
      - projects
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjetCreateErrorResponse'
          description: ''
    post:
      operationId: createProject
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectCreateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ProjectCreateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProjectCreateRequest'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProjectSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjetCreateErrorResponse'
          description: ''
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjetCreateErrorResponse'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjetCreateErrorResponse'
          description: ''
  /api/projects/{slug}/:
    get:
      operationId: getSingleProject
      parameters:
      - in: path
        name: slug
        schema:
          type: string
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProjectSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUpdateErrorResponse'
          description: ''
    patch:
      operationId: updateProjectName
      parameters:
      - in: path
        name: slug
        schema:
          type: string
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
        required: true
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProjectUpdateRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProjectUpdateRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProjectUpdateRequest'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleProjectSuccessResponse'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUpdateErrorResponse'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUpdateErrorResponse'
          description: ''
    delete:
      operationId: archiveSingleProject
      parameters:
      - in: path
        name: slug
        schema:
          type: string
          pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      responses:
        '200':
          description: No response body
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUpdateErrorResponse'
          description: ''
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectUpdateErrorResponse'
          description: ''
components:
  schemas:
    AuthedSuccessResponse:
      type: object
      properties:
        user:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
      required:
      - user
    CSRF:
      type: object
      properties:
        details:
          type: string
      required:
      - details
    DockerImage:
      type: object
      properties:
        full_image:
          type: string
          maxLength: 255
        description:
          type: string
      required:
      - description
      - full_image
    DockerImageSearchError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        q:
          type: array
          items:
            type: string
    DockerImageSearchErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/DockerImageSearchError'
      required:
      - errors
    DockerLoginError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        username:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        registry_url:
          type: array
          items:
            type: string
    DockerLoginErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/DockerLoginError'
      required:
      - errors
    DockerLoginRequest:
      type: object
      properties:
        username:
          type: string
          maxLength: 255
        password:
          type: string
          maxLength: 255
        registry_url:
          type: string
          format: uri
      required:
      - password
      - username
    DockerLoginSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
      required:
      - success
    DockerPortCheckError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        port:
          type: array
          items:
            type: string
    DockerPortCheckErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/DockerPortCheckError'
      required:
      - errors
    DockerPortCheckRequest:
      type: object
      properties:
        port:
          type: integer
          minimum: 0
      required:
      - port
    DockerPortCheckSuccessResponse:
      type: object
      properties:
        available:
          type: boolean
      required:
      - available
    DockerSuccessResponse:
      type: object
      properties:
        images:
          type: array
          items:
            $ref: '#/components/schemas/DockerImage'
      required:
      - images
    ForbiddenResponse:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    GetRootDomain:
      type: object
      properties:
        domain:
          type: string
      required:
      - domain
    LoginError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        username:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
    LoginErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/LoginError'
      required:
      - errors
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          maxLength: 255
          minLength: 1
        password:
          type: string
          maxLength: 255
          minLength: 1
      required:
      - password
      - username
    LoginSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
      required:
      - success
    PatchedProjectUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
    Project:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
        slug:
          type: string
          maxLength: 255
          pattern: ^[-a-zA-Z0-9_]+$
        archived:
          type: boolean
        owner:
          allOf:
          - $ref: '#/components/schemas/User'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - name
      - owner
      - updated_at
    ProjectCreateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
      required:
      - name
    ProjectSuccessResponse:
      type: object
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
      required:
      - projects
    ProjectUpdateErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ProjetUpdateError'
      required:
      - errors
    ProjetCreateError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        name:
          type: array
          items:
            type: string
    ProjetCreateErrorResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ProjetCreateError'
      required:
      - errors
    ProjetUpdateError:
      type: object
      properties:
        root:
          type: array
          items:
            type: string
        name:
          type: array
          items:
            type: string
    SingleProjectSuccessResponse:
      type: object
      properties:
        project:
          $ref: '#/components/schemas/Project'
      required:
      - project
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        is_staff:
          type: boolean
          title: Staff status
          description: Designates whether the user can log into this admin site.
      required:
      - username
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
