version: "3.4"

services:
  zane-proxy:
    image: localhost:9989/caddy:2.7.6-with-sablier
    command: caddy run --resume
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019
volumes:
  caddy-data:
  caddy-config: