services:
  proxy:
    image: fredkiss3/zane-caddy-proxy:dev
    command: caddy run --resume
    logging:
      driver: "fluentd"
      options:
        mode: "non-blocking"
        fluentd-address: "unix://$HOME/.fluentd/fluentd.sock"
        fluentd-async: "true"
        fluentd-max-retries: 10
        fluentd-sub-second-precision: "true"
        tag: "{\"service_id\":\"zane.proxy\"}"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role==manager
      labels:
        zane.role: "proxy"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019
    networks:
      zane:
        aliases:
          - zane.proxy
  temporal:
    entrypoint: [ "/bin/bash", "-c", "/etc/temporal/entrypoint.sh" ]
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=zane.db
      - SERVICES=history,matching,frontend,worker
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - BIND_ON_IP=0.0.0.0
    image: temporalio/auto-setup:1.24.2
    volumes:
      - ./temporalio/dynamicconfig:/etc/temporal/config/dynamicconfig/
      - ./temporalio/entrypoint.sh:/etc/temporal/entrypoint.sh
    networks:
      zane:
        aliases:
          - zane.temporal
    ports:
      - 7233:7233
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-0.13.0
    networks:
      - zane
    stdin_open: true
    tty: true
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    networks:
      - zane
    ports:
      - 8080:8080
volumes:
  caddy-data:
  caddy-config:
networks:
  zane:
    external: true