version: "3.4"

services:
  redis:
    container_name: zane-redis
    image: redis
    ports:
      - "6381:6379"
  db:
    image: postgres:12-alpine
    container_name: zane-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zane
    ports:
      - "5434:5432"
  adminer:
    image: adminer
    container_name: zane-adminer
    restart: always
    ports:
      - 8082:8080
  redis-gui:
    image: redis/redisinsight
    container_name: zane-redis-gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8089:5540"
    volumes:
      - redisinsight:/data
volumes:
  db-data:
  redisinsight: