services:
  temporal-ui:
    depends_on:
      - temporal-server
    environment:
      - TEMPORAL_ADDRESS=zane.temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    networks:
      zane:
        aliases:
          - zane.temporal_ui
    ports:
      - 8080:8080