version: "3.4"

services:
  zane-proxy:
    image: fredkiss3/caddy-with-sablier
    command: caddy run --resume
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role==manager
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019
volumes:
  caddy-data:
  caddy-config: