services:
  zane-proxy:
    image: fredkiss3/zane-caddy-proxy:dev
    command: caddy run --resume
    logging:
      driver: "fluentd"
      options:
        mode: "non-blocking"
        fluentd-address: "unix://$HOME/.fluentd/fluentd.sock"
        fluentd-async: "true"
        fluentd-max-retries: 10
        fluentd-sub-second-precision: "true"
        tag: "{\"service_id\":\"zane.proxy\"}"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role==manager
      labels:
        zane.role: "proxy"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    environment:
      CADDY_ADMIN: 0.0.0.0:2019
    networks:
      zane:
        aliases:
          - zane.proxy
volumes:
  caddy-data:
  caddy-config:
networks:
  zane:
    external: true
    # This network is created like this :
    # `docker network create --driver overlay --attachable --subnet=10.5.0.0/16 zane`