# Generated by Django 5.2 on 2026-01-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0295_add_project_collaboration_models"),
        ("zane_api", "0312_service_zane_api_se_deploy__9e359b_idx"),
    ]

    operations = []
