# Generated by Django 5.2 on 2026-03-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0313_merge_20260117_1006"),
        ("zane_api", "0318_previewenvtemplate_stacks_to_clone"),
    ]

    operations = []
