name: Biome Check Formatting
on:
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run:  |
          cd frontend 
          pnpm install --frozen-lockfile
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.5.3
      - name: Run Biome
        run: biome check .
