name: Django Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: zane
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5434:5432
      proxy:
        image: ghcr.io/zane-ops/proxy:canary
        ports:
          - "2020:2020"
        env:
          CADDY_ADMIN: 0.0.0.0:2020
      quickwit:
        image: fredkiss3/quickwit-ci-cd:v0.8.2
        ports:
          - "7280:7280"
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Install dependencies
        run: |
          cd backend
          pip install uv==0.5.10
          source .venv/bin/activate && uv pip install -r ./backend/requirements.txt

      - name: Run tests
        run: |
          cd backend
          source .venv/bin/activate && python manage.py test --parallel
